### ISSUE TITLE
 getLastDigit

### ISSUE THREAD

**Issue by DmitryYakorev** [rolling-scopes-school/core-js-numbers#10]
Не проходит core-number getLastDigit, хотя, если делаю it.only все проходит

**Comment by DmitryYakorev** [comment]
Вот ,что пишет:
 1 failing

  1) core-js-numbers-tasks optimal implementation
       optimal implementation of getLastDigit:

      AssertionError [ERR_ASSERTION]: You need to use a different method or operator, look for the appropriate method or operator in the 
documentation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_operators#arithmetic_operators
      + expected - actual

      -false
      +true

      at Context.test (test\numbers-tests.js:650:12)
      at Context.test (extensions\it-optional.js:17:12)
      at processImmediate (node:internal/timers:466:21)

**Comment by DmitryYakorev** [comment]
нашел решение
главное слово - оптимизация
